from mpi4py import MPI
from dolfinx import io


def verify_fenicsx_mesh(file_path):
    # 1. Initialize the MPI communicator
    # FEniCSx requires this to support parallel computing out of the box
    comm = MPI.COMM_WORLD

    print(f"Attempting to load mesh from: {file_path}...")

    try:
        # 2. Read the XDMF mesh file
        # 'name="Grid"' matches the default container label generated by meshio
        with io.XDMFFile(comm, file_path, "r") as xdmf:
            mesh = xdmf.read_mesh(name="Grid")

        print("Success: File parsed cleanly!")

        # 3. Extract mesh properties using FEniCSx syntax
        # mesh.geometry.x holds the coordinate matrix [X, Y, Z] for every point
        num_vertices = mesh.geometry.x.shape[0]

        # Access the topology dimension to pull the total count of 3D elements
        dim = mesh.topology.dim
        num_cells = mesh.topology.index_map(dim).size_global

        # 4. Print verification stats
        print("\n=== FEniCSx Mesh Verification ===")
        print(f"Topology Dimension: {dim}D")
        print(f"Number of Vertices: {num_vertices}")
        print(f"Number of Volume Cells (Tetrahedrons): {num_cells}")
        print("=================================\n")
        print("Your automated pipeline mesh is valid and ready for simulations!")

    except RuntimeError as e:
        print(f"\n[Error] Failed to read mesh: {e}")
        print(
            "Tip: If it complains about 'Grid', open your .xdmf file in a text editor to check the <Grid Name='...'> attribute.")
    except Exception as e:
        print(f"\n[Unexpected Error]: {e}")


if __name__ == "__main__":
    # Ensure this file matches the exact name of the output from your svmtk_env script
    target_mesh = "simulation_mesh.xdmf"
    verify_fenicsx_mesh(target_mesh)